### ISSUE TITLE
blog page

### ISSUE THREAD

**Issue by hone-zaun** [sajidali007522/edu-website#4]
## template-blog.php

https://eduhpversiontwo.wpdeveloper.at/

1. How do you trigger the `featured-checkbox`???
    * ![grafik](https://user-images.githubusercontent.com/51439140/84682453-f19dce80-af35-11ea-9249-71124eeaaf71.png)
    * I found the keys in the Database...but this does not look like an WordPress feature.
    * This is a function a editor/admin should be able to set from the backend and therefore WordPress uses the `sticky-post`-option for the posts
      * ![grafik](https://user-images.githubusercontent.com/51439140/84683035-db444280-af36-11ea-8bbe-0e9c658a1313.png)
      * https://eduhpversiontwo.wpdeveloper.at/wp-admin/post.php?post=85&action=edit
2. I understand your idea of solving the grid for the featured-posts...it works for the moment...
    * ### But something like this should be solved whit CSS!
      * What if somebody want's to display 6 Posts there? Yes, it's not gonna happen unless somebody changes it in the code!
    * But actually one should use the backend-settings here! Because at the moment this setting is just not doing anything -.-
      * ![grafik](https://user-images.githubusercontent.com/51439140/84683906-30cd1f00-af38-11ea-903b-672fff6c398b.png)
    * ![grafik](https://user-images.githubusercontent.com/51439140/84683162-147cb280-af37-11ea-8293-d6d4eb254753.png)

**Comment by sajidali007522** [comment]
Hi @hone-zaun  
Thanks for previous tasks that you mark as completed. 
Now I am done with all your remaining parts also 
One point on Blog page

**- You circle 3 posts like one big image in left and 2 on right side**
Its because the structure created by designer so we need to keep 3 all the time and if we increase 4 or 5 then it will break the layout so this is in different query

Related to bottom of the Blog posts 
if you set in backend 10 posts per page then it mean (Most Visited + after the newsletter posts)
- there are option to show how many posts you want to show on Most Visited section like 
![image](https://user-images.githubusercontent.com/60655151/84810114-4fa8df80-b024-11ea-9caf-c0a389ca3d09.png)
above screenshot 

so 10-4 is equal to 6
Its because we need to follow the design and if you go to category or other items then its showing properly one by one. 

Hope you get my point, 
and all other points are done.

**Comment by hone-zaun** [comment]
@sajidali007522 Thank you! We will use it like it is for now.

## We will fix this issue on our own during the implementation of the translation functions!

Just two more thoughts on that:

1. Yeah, I know. The design proposal does not take into account, that one might want to change the number of these 3 Posts on top of the page.
    * ### But people who work with this theme expect that they can set more or less posts there!
      * You can't seriously tell customers that they are limited to something like that.
    * The problem here is not the design, it's the code.
      * https://eduhpversiontwo.wpdeveloper.at/
      * ![grafik](https://user-images.githubusercontent.com/51439140/84825176-5550f600-b021-11ea-995b-70fa691f2bd9.png)
    * It might be the quickest solution for that problem, but just **not usable in the real world** -.-
2. And we definitely get in trouble with this as it does not only break the styles when you set 2 posts **sticky**.
    * https://eduhpversiontwo.wpdeveloper.at/
      * ![grafik](https://user-images.githubusercontent.com/51439140/84829063-66046a80-b027-11ea-8456-8feb1480ef9c.png)
    * I'm talking about the fact, that the user needs to use proper images and text.
      * And we both know we can't rely on that ;-)
